{% set name = "Flask-OpenID" %}
{% set version = "1.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5a8ffe1c8c0ad1cc1f5030e1223ea27f8861ee0215a2a58a528cc61379e5ccab

build:
  number: 3
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip

  run:
    - python
    - flask >=0.3  # [py2k]
    - flask >=0.10.1  # [py3k]
    - python-openid >=2.0  # [py2k]
    - python3-openid >=2.0  # [py3k]

test:
  imports:
    - flask_openid

about:
  home: http://github.com/mitsuhiko/flask-openid/
  license: BSD 3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: 'OpenID support for Flask'
  dev_url: http://github.com/mitsuhiko/flask-openid/
  doc_url: https://pythonhosted.org/Flask-OpenID/

extra:
  recipe-maintainers:
    - pmlandwehr
    - halldc
