travis:
  secure:
    BINSTAR_TOKEN: SNDE4sANjEFx3+68i1HJR7onAbY5ufs3Mk7pDc1Kjzmuk0K0oimHl3EfRtXEFNiYYGRcl42/IsM/lXOmmkG9/Ybpjx/Vvt1fCQQkF/nBCc97dnuL1oxeM2aE/qk/4WbiqA1rWA903mb3FO6BI2zlZqzcqvxjxotNAUhXJt47L50v4Fv6g6Vm/NKVyccBT/WFAmH41N/yVoj72R7k/eQEv6vz5VK5Xlt+X8n8mKTttodNLQUFidjwVQY0nSUWKpvV1H4z/9dvxgsc9SukbE/g1Fdh85sHm6qqcJcqPVcV+67SO5oPmWr0QFMIOhRyUzdWLvCuVwcpOzeRmswIkroyyfNi65pKcf3Wokbd+TRIRRZnUldiZ7AyLQM7uSaVpeBAFrenPMku7zHKLiPKTq30jilK1y9yYqjFmD90ZamqvF/gcX4yNde8dl9anKHvRWaCoN0le2FddXcdGLiXI5V1NH6nE2HCTV+/TPB0AoG7lSlgtEv88s7d6WgMr60Hma9aQY0LGRPLZdceqtrXMIPoNv79LiwZJ3NYyoHWqJedd6iOaEDAJlnCLawgo5pgnkrNUuATNDtxA8bsBVpa2flnoMEmZe6o0CqTJZu8ArC+TjHYDI9xWjrYOBmAqs61mLFHme4JEMUnIUZDhDchvAT8jJzN8uQDt3bQArHRPOgP8gQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
